---
version: '3'
services:
    app:
        build:
            context: ./Docker
            dockerfile: Dockerfile
        restart: 'on-failure'
        ports:
            - '8080:8080'
        depends_on:
          - db

    db:
        image: mysql:5.7
        restart: 'on-failure'
        ports:
          - '8514:8514'
        environment:
          MYSQL_ROOT_PASSWORD: 'secret'
          MYSQL_DATABASE: 'dd'
        volumes:
          - db:/var/lib/mysql

volumes:
    db: